def count_nucleotides(sequence):
    counts = {}
    counts['A'] = 0
    counts['C'] = 0
    counts['G'] = 0
    counts['T'] = 0
    for i in range(0, len(sequence)):
        counts[sequence[i]] += 1
    print(counts['A'], counts['C'], counts['G'], counts['T'])


count_nucleotides('AAGTAGACGTCATGAAGCCCGCAATTCGACACTTGTTGAAGAGGATCAGCTACAGCAAGTACAAAAACTTGGCTAATGATCCTATGTTTTGGCTATTTAATCCTCTATCCCTGTATGAAGCGGATGTATCCCCGGGGTACCCATTTGCGGTATGCCTCAAATTTTCTGAACCACCACAGCGGAGCCCTTAGCTAGGCGGGCATATGAACGCAGGAAGGATTGCAAAAATGACTTCAAGTAAGGCATTCCTCAGAGTCGATTAAATCTCATGGCTACAATACGAGCGGAGCGATGAAGTCAATCTATGACTTGTAGGGCTTCATACACGAATTGAGCAAAAATATAAAACGTAGGTTGTATGAAGTGGATCCTGGCTCAAATGAGTAGTTGGTCCGAAGAATTTTAGATGGCAGTTAAATGCTCATCAGAGCGCACTACATATTGCAGCCATTTTTGGGTTATCCAGTTAATCCACTTCACGGTCGAAGTCCTAGATGCGTTGGGTTGACTAGGAGGCTGGATGTAGACAGCGTCCAGAGCCCTAGGCCATGCATACGTCTCGTGCAAACCGTGTACATGAGTCAGTTGGGCGCGGTGGTATTTACCCGCTTCTACCCGCGCGCGGCAGCTTGTAGCATGAGTTACACTGCACACGGCACAAAGACAAATGGCGTAATTTCGCCTGAACATCATCTCTTGCCCCTCCACCTACATATTTCTGTAAACTGTGAGCAGTGCCAGACCTGTTAGCACAGTAAATTTCCCTGATGTCTCGCGAAGTTCTCGGATTCTGGCTTGGGTTACGCGTCCGGTGGGTCATTCAATCGTGGGATCTGTCTTGGTAAGTGCAGGCCTGGTGATTCAAT')

