def reverse_complement_dna(dna):
    reverse = dna[::-1]
    rev_comp = ''
    for i in range(0, len(reverse)):
        nucleotide = reverse[i]
        if nucleotide == 'A':
            rev_comp += 'T'
        elif nucleotide == 'T':
            rev_comp += 'A'
        elif nucleotide == 'C':
            rev_comp += 'G'
        elif nucleotide == 'G':
            rev_comp += 'C'
    print(rev_comp)


reverse_complement_dna('CGTCGGACGCATCTCGTCTCTGTAGCTGGGGTACTTCTAGCCCACGAGTTACTACACTGGGCTATCTTTAACACACGACGACCTACTCACTAAGGCGAGATACTGAAGAAAAAGGAGCATATGGCCCCCCGCCAGTCACGTATAGCTGGTTAAGGGAAAGGTATCGCAGGTACTCTTGTGATATATTACATGAATGCCGATTTCATCTGGCGACGTGCCGTAATGGAACGATTCGCGTAACATCAGCCAGGTACCGTGTAACTCTGCCCCGGCTGGGAACCGTACCGCTTACAGTAGCTGACATAGACGCATAACAACTACACCGGGCCAACTCCATCCCTGTAATGGCTTACGAGTACGCGAGAGCGTTTTCGATTCAGTTCGGAACGACACAGCGGTTGGAAGTCGAGGAGCAGGTAATCAAATTCATCTGGGAGGGAGCATTTTGACACCGTAGCACGGGTGGAAAACTAGCAGCGTCGCTTCGGGCGCTGTTTCTGGCACACACTCTTTTGACTCCTGAATACTTGAGGTTTTGTCCTATCCCAGTAAAACGCCTGTGCAGTGCAAGCCTCCTTTCTATTGGAGATCACACTTAGTATTAGCAAGGTCGACAGACTCCGACCAGCGGGACTTCTAGACCCGGGAGGCATTGACGTAGTGGGAGACCTGGGGCCTATGGCCTTACATCCACTGCATATGCCATCGTCAAGATTATATTGCATCGTCCAAAGTTACGCTGCAGTGGCCCAGAATAGCGCCCTAACAAGCACCCGACAATAGTAGCGACCGAAAAAACGTCATTTTATAAATGATTGTCCCAATTTATGAGCGGCCTTGGCTCCAACTCGAACTGACGGGTCAGTACACATTAGAATGCAAAAGTAGTTAAGACACCAAGTAACGGCGCTGCAACTTGGCAGACTGGCTTGTGTCGATTCGAAGGGCAACAGTCGCGCTAGTTATCTGGGTGACTCAGGT')